approvals:
  # PR needs at least 2 approvals
  minimum: 2
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍)$"
  # note that `from` is by default empty,
  # accepting any matching comment as approval
  from:
    # commenter must be either one of:
    orgs:
      # a member of zalando organization
      # (any org in here counts)
      - "zalando"
    # OR a collaborator of the repo
    collaborators: true

X-Zalando-Team: "norris"
X-Zalando-Type: "code"
